import { MappingConfig } from '../types';

/** Proste mapowanie: pozycja rąk, rozstaw, kąty łokci, prędkość ruchu → dźwięk */
export const presets: Record<string, MappingConfig> = {
  default: {
    id: 'default-simple',
    name: 'Conductor',
    description: 'Wysokość rąk → ton, rozstaw → filtr, ruch → głośność',
    rules: [
      {
        source: 'leftHandHeightRel',
        target: 'osc1Frequency',
        inputMin: -0.85,
        inputMax: 0.85,
        outputMin: 130,
        outputMax: 920,
        curve: 1.1,
        weight: 1,
      },
      {
        source: 'rightHandHeightRel',
        target: 'osc2Frequency',
        inputMin: -0.85,
        inputMax: 0.85,
        outputMin: 110,
        outputMax: 680,
        curve: 1,
        weight: 1,
      },
      {
        source: 'bodyOpenness',
        target: 'filterCutoff',
        inputMin: 0.15,
        inputMax: 0.9,
        outputMin: 420,
        outputMax: 6200,
        curve: 1.2,
        weight: 1,
      },
      {
        source: 'handsDistance',
        target: 'delayTime',
        inputMin: 0.08,
        inputMax: 0.75,
        outputMin: 0.12,
        outputMax: 0.42,
        curve: 0.7,
        weight: 1,
      },
      {
        source: 'leftElbowAngle',
        target: 'filterResonance',
        inputMin: 35,
        inputMax: 165,
        outputMin: 0.4,
        outputMax: 9,
        weight: 0.6,
      },
      {
        source: 'rightElbowAngle',
        target: 'filterResonance',
        inputMin: 35,
        inputMax: 165,
        outputMin: 0.4,
        outputMax: 9,
        weight: 0.6,
      },
      {
        source: 'overallMovement',
        target: 'masterVolume',
        inputMin: 0.02,
        inputMax: 0.85,
        outputMin: 0.16,
        outputMax: 0.92,
        curve: 0.5,
        weight: 1,
      },
      {
        source: 'overallMovement',
        target: 'filterCutoff',
        inputMin: 0.04,
        inputMax: 0.8,
        outputMin: 700,
        outputMax: 7800,
        curve: 0.55,
        weight: 0.45,
      },
      {
        source: 'leftHandSide',
        target: 'pan',
        inputMin: -0.85,
        inputMax: 0.85,
        outputMin: -0.75,
        outputMax: 0.75,
        weight: 0.5,
      },
      {
        source: 'rightHandSide',
        target: 'pan',
        inputMin: -0.85,
        inputMax: 0.85,
        outputMin: -0.75,
        outputMax: 0.75,
        weight: 0.5,
      },
    ],
  },

  energetic: {
    id: 'energetic-simple',
    name: 'Energetic',
    description: 'Szybki ruch i rozstaw rąk',
    rules: [
      {
        source: 'handsDistance',
        target: 'osc1Frequency',
        inputMin: 0.1,
        inputMax: 0.8,
        outputMin: 180,
        outputMax: 1200,
        curve: 1.4,
        weight: 1,
      },
      {
        source: 'overallMovement',
        target: 'masterVolume',
        inputMin: 0.03,
        inputMax: 0.9,
        outputMin: 0.2,
        outputMax: 0.95,
        weight: 1,
      },
      {
        source: 'leftHandHeightRel',
        target: 'filterCutoff',
        inputMin: -0.7,
        inputMax: 0.75,
        outputMin: 600,
        outputMax: 8500,
        weight: 1,
      },
      {
        source: 'rightHandSide',
        target: 'pan',
        inputMin: -0.85,
        inputMax: 0.85,
        outputMin: -0.9,
        outputMax: 0.9,
        weight: 1,
      },
    ],
  },

  atmospheric: {
    id: 'atmospheric-simple',
    name: 'Atmospheric',
    description: 'Wolne, przestrzenne tekstury',
    rules: [
      {
        source: 'torsoCenterY',
        target: 'osc1Frequency',
        inputMin: 0.35,
        inputMax: 0.8,
        outputMin: 90,
        outputMax: 220,
        curve: 0.6,
        weight: 1,
      },
      {
        source: 'bodyOpenness',
        target: 'filterCutoff',
        inputMin: 0.2,
        inputMax: 0.85,
        outputMin: 300,
        outputMax: 2100,
        curve: 0.5,
        weight: 1,
      },
      {
        source: 'handsDistance',
        target: 'delayTime',
        inputMin: 0.1,
        inputMax: 0.6,
        outputMin: 0.22,
        outputMax: 0.72,
        curve: 0.4,
        weight: 1,
      },
      {
        source: 'overallMovement',
        target: 'masterVolume',
        inputMin: 0.02,
        inputMax: 0.6,
        outputMin: 0.12,
        outputMax: 0.7,
        weight: 0.8,
      },
    ],
  },
};

export function getPreset(name: keyof typeof presets): MappingConfig {
  return presets[name] ?? presets.default;
}